version: '3.7'



services:



  react:

    container_name: simplitask

    build:

      context: .

      dockerfile: Dockerfile

    volumes:

      - '.:/app'

      - '/app/node_modules'

    ports:

      - 80:3000 

    environment:

      - CHOKIDAR_USEPOLLING=true